export const FLAG_TYPE = {
  IS_FIRST_TIME_USER: "IS_FIRST_TIME_USER",
  EMAIL_VERIFICATION_STATUS: "EMAIL_VERIFICATION_STATUS",
  ALL_INITIAL_SETUP_COMPLETED: "ALL_INITIAL_SETUP_COMPLETED",
};

export const STATUS = {
  COMPLETED: "COMPLETED",
  PENDING: "PENDING",
  TRUE: "TRUE",
  FALSE: "FALSE",
};
