export const FLAG_TYPE = {
  AUTHENTICATED_USER: "AUTHENTICATED_USER",
  EMAIL_VERIFICATION_STATUS: "EMAIL_VERIFICATION_STATUS",
};

export const STATUS = {
  COMPLETED: "COMPLETED",
  PENDING: "PENDING",
  TRUE: "TRUE",
  FALSE: "FALSE",
};
