export const API = {
  UI_CARDS: "/cards",
  REGISTER: "/customer/profile",
  GET_CUSTOMER: "/customer/profile",
  CUSTOMER_EXISTS: "/customer/exist",
  PUT_CUSTOMER: "/customer/profile",
  PUT_ADDRESS: "/customer/property",
  DELETE_CUSTOMER: "/customer/delete",
  DELETE_ADDRESS: "/customer/property/remove",
  GET_HOUSE_INFO: "/houseinfo",
  GET_SERVICES: "/services",
  GET_APPOINTMENTS: "/customer/appointments",
  POST_LEAD: "/leads",
  PUT_LEAD: "/leads",
  GET_LEAD: "/leads",
  GET_SERVICE_COST: "/services/cost",
  GET_SAVED_CARDS: "/payment/cards",
  SAVE_CARD: "/payment/savecard",
  CREATE_ORDER_FROM_LEAD: "/orders",
  GET_ALL_ORDERS: "/orders/all",
  CANCEL_ORDER: "/orders",
  RESCHEDULE_ORDER: "/orders",
  GET_ORDER_DETAILS: "/orders",
  VALIDATE_COUPON: "/coupon/validate",
  SEND_MESSAGAE: "/comments",
  GET_INVITED_USERS: "/customer/invitedusers",
  INVITE_USER: "/customer/invitenewuser",
};
