export const API = {
  REGISTER: "/customer/profile",
  GET_CUSTOMER: "/customer/profile",
  PUT_CUSTOMER: "/customer/profile",
  GET_HOUSE_INFO: "/houseinfo",
  GET_SERVICES: "/services",
  GET_APPOINTMENTS: "/customer/appointments",
  POST_LEAD: "/leads",
  PUT_LEAD: "/leads",
  GET_LEAD: "/leads",
  GET_SERVICE_COST: "/services/cost",
  GET_SAVED_CARDS: "/payment/cards",
  SAVE_CARD: "/payment/savecard",
  CREATE_ORDER_FROM_LEAD: "/orders",
  GET_ALL_ORDERS: "/orders/all",
  GET_ORDER_DETAILS: "/orders",
  VALIDATE_COUPON: "/coupon/validate",
};
