require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

$FirebaseSDKVersion = '8.12.1'
$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'MioHomeServices' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'GoogleSignIn', '~> 6.1.0'
  

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  target 'MioHomeServicesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # installer.aggregate_targets.each do |aggregate_target|
    #   aggregate_target.user_project.native_targets.each do |target|
    #     target.build_configurations.each do |config|
    #       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    #       config.build_settings['EXCLUDED_ARCHS'] = 'i386'
    #     end
    #   end
    #   aggregate_target.user_project.save
    # end
  end

  
end